services:
  location-extraction:
    container_name: location-extraction-service
    image: living-map/location-extraction-service
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgres://livingmap:livingmap@postgres:5432/livingmap
      - SPACY_EN_MODEL=en_core_web_sm
      - SPACY_FR_MODEL=fr_core_news_sm
