name: Install scw CLI
description: Install and configure Scaleway CLI
inputs:
  scw-access-key:
    required: true
  scw-secret-key:
    required: true
  scw-organization-id:
    required: true
  scw-project-id:
    required: true
runs:
  using: composite
  steps:
    - run: curl -sL https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
      shell: bash
    - run: scw init access-key=${{ inputs.scw-access-key }} secret-key=${{ inputs.scw-secret-key }} organization-id=${{ inputs.scw-organization-id }} project-id=${{ inputs.scw-project-id }} send-telemetry=false
      shell: bash
